### ISSUE TITLE
Error on Android

### ISSUE THREAD

**Issue by fvermeulen** [voxdev/Xamarin.Plugins#4]
Hey @rjcollingham 
I got that error message, when i tested it on android. Something went wrong with the IRatingService

I set everything up like in your sample app
Can you explain me the problem?

`[MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] System.MissingMethodException: Default constructor not found for type StoreRating.Forms.Plugin.Droid.RatingService
[MonoDroid] at System.Activator.CreateInstance (System.Type,bool) <IL 0x000ae, 0x003a4>
[MonoDroid] at System.Activator.CreateInstance (System.Type) <IL 0x00002, 0x00067>
[MonoDroid] at Xamarin.Forms.DependencyService.Get<StoreRating.Forms.Plugin.Abstractions.IRatingService> (Xamarin.Forms.DependencyFetchTarget) <0x0032b>
[MonoDroid] at StoreRating.Forms.Plugin.Abstractions.StoreRatingControl.ShowStore () [0x00000] in c:\Projects\Internal\StoreRating\StoreRating\StoreRating.Forms.Plugin.Abstractions\StoreRatingControl.cs:445
[MonoDroid] at StoreRating.Forms.Plugin.Abstractions.StoreRatingControl.<ShowRating>b__7 (object,System.EventArgs) [0x00006] in c:\Projects\Internal\StoreRating\StoreRating\StoreRating.Forms.Plugin.Abstractions\StoreRatingControl.cs:299
[MonoDroid] at Xamarin.Forms.Button.Xamarin.Forms.IButtonController.SendClicked () <IL 0x00027, 0x0015b>``

**Comment by rjcollingham** [comment]
Hi, did you add the 2 Init lines to the MainActivity.cs file after the Forms.Init line?

The error is on the dependency call to the Android implementation of RatingService

If you don't include the Init lines the compiler will not link with the libraries

**Comment by fvermeulen** [comment]
@rjcollingham 

Yes it was directly after the Forms.Init()

I used Xamarin Forms 1.4.2

**Comment by fvermeulen** [comment]
Oh it was a Linker problem. Our project in android is set to link all assemblies

Thank you
